language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g bower purescript pulp
  - npm install
  - bower install --production
script:
  - npm run -s clean
  - npm run -s build
after_success:
- >-
  echo $TRAVIS_TAG
  echo $GITHUB_TOKEN 
